# Generated by Django 5.2.1 on 2025-05-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home & Living'), ('other', 'Other'), ('entertainment', 'Entertainment')], default='other', max_length=20),
        ),
    ]
